language: generic
sudo: required
services:
  - docker

before_install:
# -t (tag the container,-f force the build to use .dev instead of the default file)
  - docker build -t talbendet/docker-react -f Dockerfile.dev .  

script:
  # travis is watching the output of each command,if it returns status code of Zero it assume the test/build failed
  - docker run -e CI=true talbendet/docker-react npm run test
  # CI=true - The test command will force Jest to run in CI-mode, and tests will only run once instead of launching the watcher.
  # -e sets an environment variable

deploy:
  # travis has some pre sets for deployment 
  provider: elasticbeanstalk
  region : "us-west-2"
  # the name of the app on aws
  app: "docker-react"
  env: "Dockerreact-env"
  # !what is a bucket?
  bucket_name: "elasticbeanstalk-us-west-2-964311154337"
  bucket_path: "docker-react"
  # only build when pushed to master branch
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

