FROM node:alpine
 
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
 
CMD ["npm", "start"]

#! read more on volumes

# docker run -it -p 3000:3000 -v /home/node/app/node_modules -v /home/t-bendet/frontend:/home/node/app talbendet:frontend

